services:
  virtuoso:
    image: openlink/virtuoso-opensource-7:latest
    container_name: virtuoso
    ports:
      - "8890:8890"
      - "1111:1111"
    environment:
      DBA_PASSWORD: dba
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://sepses.local"
      VIRT_Parameters_DirsAllowed: ".,../vad,/usr/share/proj,/database,/opt/virtuoso-opensource/vad"

    volumes:
      - ./virtuoso-data:/database
    healthcheck:
      test: ["CMD-SHELL", "/opt/virtuoso-opensource/bin/isql", "1111", "dba", "dba", "exec=status();"]
      interval: 15s
      timeout: 10s
      retries: 10
    restart: unless-stopped
