from langchain.prompts import PromptTemplate

from backend.sparql.client import run_query, bindings_to_rows
from backend.llm.llm_models import (LLMProvider, DEFAULT_MODEL)
from backend.sparql.ontology_context import (ONTOLOGY_CONTEXT)
import re


template = """
You are a cybersecurity SPARQL expert.

- Translate the user question into valid SPARQL.
- Use the ontology below.
- Return ONLY SPARQL query.

Ontology:
{ontology}

Question:
{question}

SPARQL:
"""


prompt = PromptTemplate(
    input_variables=["ontology", "question"],
    template=template
)

# Simple Regex Fast Path
def regex_sparql(question: str):

    # Cari CVE ID
    cve_match = re.search(r"(CVE-\d{4}-\d+)", question, re.IGNORECASE)
    if cve_match:
        cve_id = cve_match.group(1).upper()
        return f"""
PREFIX cve: <http://w3id.org/sepses/vocab/ref/cve#>

SELECT ?description
WHERE {{
    ?cve cve:cveId "{cve_id}" ;
         cve:description ?description .
}}
LIMIT 10
"""
    # Tidak cocok regex
    return None

# LLM Generator
def llm_generate(question: str):
    llm = LLMProvider.get_model(DEFAULT_MODEL)
    chain = prompt | llm

    response = chain.invoke({
        "ontology": ONTOLOGY_CONTEXT,
        "question": question
    })
    return response.content.strip()

# Extract SPARQL
def extract_sparql(text: str):

    # Ambil isi ```sparql ```
    match = re.search(
        r"```(?:sparql)?\s*([\s\S]+?)```",
        text,
        re.IGNORECASE
    )

    if match:
        return match.group(1).strip()

    return text.strip()

# Validate SPARQL

def validate_sparql(query: str):
    query_upper = query.upper()

    return (
        "SELECT" in query_upper and
        "WHERE" in query_upper and
        "{" in query and
        "}" in query
    )

# Main Converter
def generate_sparql(question: str):

    # 1. Regex fast path
    query = regex_sparql(question)
    if query:
        method = "regex"
    else:
        # 2. LLM fallback
        raw_output = llm_generate(question)

        query = extract_sparql(raw_output)

        if not validate_sparql(query):
            raise ValueError("Invalid SPARQL generated by LLM")

        method = "llm"

    return query, method

# Execute Query
def execute_question(question: str):
    sparql_query, method = generate_sparql(question)
    raw_result = run_query(sparql_query)

    rows = bindings_to_rows(raw_result)

    return {
        "question": question,
        "method": method,
        "sparql": sparql_query,
        "results": rows
    }

# Demo
if __name__ == "__main__":
    q = "Show vulnerabilities related to CVE-2021-44228"

    result = execute_question(q)

    print("QUESTION:")
    print(result["question"])

    print("\nSPARQL:")
    print(result["sparql"])

    print("\nRESULTS:")
    for r in result["results"]:
        print(r)

    execute_nl_query = execute_question